###
GET http://localhost:4000/users

###
POST http://localhost:4000/users
Content-Type: application/json

{
  "name": "Anurag",
  "password": "password"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
  "name": "Anurag",
  "password": "password"
}

###
DELETE http://localhost:4000/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQW51cmFnIiwicGFzc3dvcmQiOiIkMmIkMTAkeGo3MlE4b3kxOXJtQU5vL25QaGpiZVphZElqemVyUGxXajZVMExkeW1YMzBEVjI1bkM5QTIiLCJpYXQiOjE2NDgzNjYyMTR9.6lS7P2cxNIxh6XJxObnPuN55k4RO1_p4iYBmHiWbLs8"
}

###
POST http://localhost:4000/token
Content-Type: application/json

{
  "token": "123"
}

###
GET http://localhost:3000/posts
Authorization: Bearer 123